### ISSUE TITLE
We should remove our dependency on `@angular/flex-layout`

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-iteration-template#1283] opened 2023-02-02 00:07 UTC
[The Angular folks have stopped working on/supporting this package](https://blog.angular.io/modern-css-in-angular-layouts-4a259dca9127), which never actually made it out of beta. I'm not sure if we actually use/need it, or in what way, but we should remove our dependency on it and (if necessary) figure out what a reasonable alternative might be.

This issue also exists in [Lab 3](https://github.com/UMM-CSci-3601/3601-lab3_angular-javalin/issues/1049) and Lab 4.

**Comment by kklamberty** [comment] 2023-02-02 00:45
I think this is a bit of a repeat of #1246 where I've also added some comments with resources about how to do that.

**Comment by floogulinc** [comment] 2023-02-02 05:35
Indeed it is a duplicate of #1246

**Closed** 2023-02-02 05:36 UTC

**Comment by NicMcPhee** [comment] 2023-02-02 18:51
Oops – sorry. Thanks for cleaning this up.
